spring:
  datasource:
    url: jdbc:mysql://localhost:3306/players-search?createDatabaseIfNotExist=true&characterEncoding=UTF-8&engine=InnoDB
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  level:
    - debug