spring:
  datasource:
    url: jdbc:${JAWSDB_URL}
    username: ${JAWSDB_USER}
    password: ${JAWSDB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off
  application:
    name: @artifactId@
logging:
  file:
    name: teste
  level:
    - debug