spring:
  datasource:
    url: jdbc:mysql://localhost:3306/players-search?createDatabaseIfNotExists?true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  main:
    banner-mode: off
  application:
    name: @artifactId@
logging:
  file:
    name: teste
  level:
    - debug